### ISSUE TITLE
Add powerups

### ISSUE THREAD

**Issue by johnsonb2** [mrsell/css385_winter_unity_game#25]
Estimated Time: 80
Min. Time: 50
Max. Time: 130

**Comment by mrsell** [comment]
Supporting comments from Sprint #1 feedback:

"Maybe collecting food items along the way could spawn a better weapon that is the shape of what the recipe would've made."

"Implement different mechanics like movement options, powerups, modify scrolling, a method of defending yourself from shots."

"Add power ups, bosses, different types of enemies"

"Power Ups"

**Comment by Extrosis** [comment]
The player has three abilities that act as powerups. However, we should probably discuss if we should implement powerups that you can collect on the map.
