### ISSUE TITLE
Implement consequence for passing an enemy

### ISSUE THREAD

**Issue by mrsell** [mrsell/css385_winter_unity_game#33]
From Sprint #1 feedback:

"Not having any consequences for letting the enemies pass/defeating them doesn't really
give the player a reason to play the game in the first place."

"How to handle enemies that move past the player"

"Implementing tracker or consequence system if enemy gets pass player"

"There needs to be some sort of incentive for killing the enemies. If you can just dodge
the enemies by going to the side of the map they arent on and then scroll to the end it
doesnt make very much sense."

"Maybe have it so that your screen does not move up until all the enemies at the
current level are not fed yet?"

"have enemies follow you even if you passes them"

**Comment by Extrosis** [comment]
One consequence is implemented: Despawning enemies not defeated by the player should decrement the score. However, from testing, I believe there are bugs.

**Comment by johnsonb2** [comment]
Not implemented
