### ISSUE TITLE
Implement multi-directional shooting

### ISSUE THREAD

**Issue by mrsell** [mrsell/css385_winter_unity_game#35]
From Sprint #1 feedback:

"I would implement it so that you can shoot in multiple locations"

"I would consider alternate ways to fire, including directions. Currently the only way to
fire is to stand directly in the path of fire from an emery."

**Comment by mrsell** [comment]
An example from a classic:

https://www.youtube.com/watch?v=l800GL6NQPY

(starting at 4:10)

**Comment by johnsonb2** [comment]
Not implemented
