### ISSUE TITLE
Find some initial artwork/assets

### ISSUE THREAD

**Issue by mrsell** [mrsell/css385_winter_unity_game#6]

**Comment by Extrosis** [comment]
I should leave the things I found here:
- Candy
https://opengameart.org/content/candy-pack-1

- Vegetables
https://opengameart.org/content/platformer-pickups-pack

- Trucks
https://opengameart.org/content/saucy-trucks

- General Food
https://opengameart.org/content/food-items-16x16
https://opengameart.org/content/icons-food

**Comment by mrsell** [comment]
Thanks for the Open Game Art tip!
